name = "dom13-qform-notion"
main = "src/index.js"
compatibility_date = "2026-10-10"
workers_dev = true

# All credentials and webhook path secrets MUST be set using
# Cloudflare Workers > Settings > Variables and Secrets, type Secret.
# NOTION_DATA_SOURCE_ID may be stored as a normal variable.
[vars]
NOTION_DATA_SOURCE_ID = "9f0d20ce-441c-4d6e-b833-0bfe4bfcca21"
